# students=("Rohan","aman","Swastik","Krish")
students={"Aman": 66,"swastik":78,"Krish":92,"Lakshay":98}
print(students)
a=students.items()
print(a)
b=students.keys()
print(b)
c=students.values()
print(c)
d=students.pop("Krish")
print(d)
e=students.popitem()
print(e)
students.clear()
print(students)