Marks =[]
M1=input("Enter your marks: ")
Marks.append(M1)
M2=input("Enter your marks: ")
Marks.append(M2)
M3=input("Enter your marks: ")
Marks.append(M3)
M4=input("Enter your marks: ")
Marks.append(M4)
M6=input("Enter your marks: ")
Marks.append(M6)
M6=input("Enter your marks: ")
Marks.append(M6)
sort=Marks.sort()
print(Marks)
