marks=[]
marks1=int(input("Enter marks1: "))
marks.append(marks1)
marks2=int(input("Enter marks2: "))
marks.append(marks2)
marks3=int(input("Enter marks3: "))
marks.append(marks3)
marks4=int(input("Enter marks4: "))
marks.append(marks4)
marks5=int(input("Enter marks5: "))
marks.append(marks5)
marks6=int(input("Enter marks6: "))
marks.append(marks6)
marks.sort()
print(marks)
